#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Appzcoder\PHPCloc\Commands\ClocCommand;
use Appzcoder\PHPCloc\Commands\DuplicateCommand;
use Symfony\Component\Console\Application as BaseApplication;

final class Application extends BaseApplication
{
    /**
     * {@inheritdoc}
     */
    public function getLongVersion()
    {
        return 'PHPCloc by <comment>Sohel Amin <https://github.com/sohelamin></comment>';
    }
}

$application = new Application();

$application->add(new ClocCommand());
$application->add(new DuplicateCommand());

$application->run();
